name: 'nyc_taxi_gold'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi_gold'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_taxi_gold:
    staging:
      +materialized: view
    gold:
      +materialized: table

seeds:
  nyc_taxi_gold:
    taxi_zone_lookup:
      +column_types:
        location_id: INT64
