nyc_taxi_gold:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth            # use service-account in CI (set GOOGLE_APPLICATION_CREDENTIALS)
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: gold_star_schema
      location: us-central1
      threads: 4
      timeout_seconds: 300
