terraform {
  required_version = "1.15.8"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 5.0"
    }
  }

  # Bucket is created out-of-band; Terraform cannot manage its own state store.
  backend "gcs" {
    bucket = "gitops-iceberg-data-platform-tfstate"
    prefix = "terraform/demo"
  }
}

# Generated by config/load.py (`make resolve`); the only source of project and region.
locals {
  cfg = yamldecode(file("${path.module}/../../../config/resolved.yaml"))
}

provider "google" {
  project = local.cfg.project_id
  region  = local.cfg.region
}

provider "google-beta" {
  project = local.cfg.project_id
  region  = local.cfg.region
}

resource "google_bigquery_dataset" "ops" {
  dataset_id                 = "ops"
  location                   = local.cfg.region
  delete_contents_on_destroy = true
}

output "ops_dataset_id" {
  value = google_bigquery_dataset.ops.dataset_id
}
