terraform {
  required_version = "1.16.5"

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "8.6.0"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "8.6.0"
    }
  }

  # Bucket is created out-of-band; Terraform cannot manage its own state store.
  backend "gcs" {
    bucket = "gitops-iceberg-data-platform-tfstate"
    prefix = "terraform/demo"
  }
}

# Generated by config/load.py (`make resolve`); the only source of project and region.
locals {
  cfg = yamldecode(file("${path.module}/../../../config/resolved.yaml"))
}

provider "google" {
  project = local.cfg.project_id
  region  = local.cfg.region
}

provider "google-beta" {
  project = local.cfg.project_id
  region  = local.cfg.region
}

# Principals allowed to impersonate the deploy and runtime SAs. Identities are not
# committed: `make tf-apply` passes the active gcloud account.
variable "impersonators" {
  description = "IAM members allowed to impersonate the deploy and runtime SAs"
  type        = list(string)
}

module "iam" {
  source        = "../../modules/iam"
  project_id    = local.cfg.project_id
  impersonators = var.impersonators
}

module "storage" {
  source         = "../../modules/storage"
  project_id     = local.cfg.project_id
  region         = local.cfg.region
  runtime_member = module.iam.runtime_sa_member
}

resource "google_bigquery_dataset" "ops" {
  dataset_id                 = "ops"
  location                   = local.cfg.region
  delete_contents_on_destroy = true
}

module "bq_ops" {
  source         = "../../modules/bq_ops"
  project_id     = local.cfg.project_id
  region         = local.cfg.region
  ops_dataset_id = google_bigquery_dataset.ops.dataset_id
}

output "ops_dataset_id" {
  value = google_bigquery_dataset.ops.dataset_id
}

output "deploy_sa_email" {
  value = module.iam.deploy_sa_email
}

output "runtime_sa_email" {
  value = module.iam.runtime_sa_email
}

output "dashboard_sa_email" {
  value = module.iam.dashboard_sa_email
}

output "landing_bucket" {
  value = module.storage.landing_bucket
}

output "warehouse_bucket" {
  value = module.storage.warehouse_bucket
}

output "iceberg_catalog" {
  value = module.storage.iceberg_catalog
}

output "steward_dataset_id" {
  value = module.bq_ops.steward_dataset_id
}

output "mpi_eval_dataset_id" {
  value = module.bq_ops.mpi_eval_dataset_id
}
