apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-platform-dev
  namespace: argocd
  labels:
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/JeanFraga/GitOps_Iceberg_Data_Platform.git
    targetRevision: HEAD
    path: gitops/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: data-platform-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
