"""Resolve platform config: defaults deep-merged with a profile, plus versions.yaml.

Usage: python config/load.py [--profile demo] [--validate-only | --check]
Writes config/resolved.yaml. Deep-merge logic lives only here. The `versions` key
comes only from the repo-root versions.yaml and replaces any `versions` key in
defaults or the profile.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import yaml
from jsonschema import Draft202012Validator

CONFIG_DIR = Path(__file__).resolve().parent
COST_FLAGS = ("workflows_enabled", "composer_enabled", "dataproc_schedule_enabled")
HEADER = "# GENERATED by config/load.py -- do not edit. Run `make resolve`.\n"


def deep_merge(base: dict, override: dict) -> dict:
    """Return base with override merged in; nested dicts merge, other values replace."""
    out = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def _read(path: Path) -> dict:
    data = yaml.safe_load(path.read_text()) or {}
    if not isinstance(data, dict):
        raise TypeError(f"{path} must contain a mapping")
    return data


def resolve(profile: str, config_dir: Path = CONFIG_DIR) -> dict:
    """Defaults deep-merged with the profile, plus the versions.yaml pins under `versions`."""
    profile_path = config_dir / "profiles" / f"{profile}.yaml"
    if not profile_path.is_file():
        raise FileNotFoundError(f"profile not found: {profile} ({profile_path})")
    resolved = deep_merge(_read(config_dir / "defaults.yaml"), _read(profile_path))
    versions_file = config_dir.parent / "versions.yaml"
    if versions_file.is_file():
        resolved["versions"] = _read(versions_file)
    return resolved


class ConfigError(Exception):
    """The resolved config breaks the contract."""


def validate(resolved: dict, config_dir: Path = CONFIG_DIR) -> None:
    """Raise ConfigError listing every JSON Schema violation of the resolved config."""
    schema = json.loads((config_dir / "schemas" / "profile.schema.json").read_text())
    errors = sorted(Draft202012Validator(schema).iter_errors(resolved), key=lambda e: list(e.path))
    if errors:
        lines = [f"{'.'.join(map(str, e.path)) or '<root>'}: {e.message}" for e in errors]
        raise ConfigError("schema violations:\n  " + "\n  ".join(lines))


def check_defaults(config_dir: Path = CONFIG_DIR) -> None:
    """Cost-bearing flags default off and ml_fallback_enabled defaults on (AD-1)."""
    flags = _read(config_dir / "defaults.yaml").get("flags") or {}
    bad = [f for f in COST_FLAGS if flags.get(f) is not False]
    if flags.get("ml_fallback_enabled") is not True:
        bad.append("ml_fallback_enabled")
    if bad:
        raise ConfigError(f"defaults.yaml flags off-contract: {', '.join(bad)}")


def validate_standards(config_dir: Path = CONFIG_DIR) -> None:
    """lifecycle.yaml matches its schema and its transitions form a closed graph over the states."""
    lifecycle = _read(config_dir / "standards" / "lifecycle.yaml")
    schema = json.loads((config_dir / "schemas" / "lifecycle.schema.json").read_text())
    errors = [e.message for e in Draft202012Validator(schema).iter_errors(lifecycle)]
    if not errors and set(lifecycle["transitions"]) != set(lifecycle["states"]):
        errors.append("transitions must list every state exactly once")
    if errors:
        raise ConfigError("lifecycle.yaml violations:\n  " + "\n  ".join(errors))


def render(profile: str, config_dir: Path = CONFIG_DIR) -> str:
    """Validated resolved.yaml text for a profile."""
    resolved = resolve(profile, config_dir)
    check_defaults(config_dir)
    validate(resolved, config_dir)
    return HEADER + yaml.safe_dump(_sorted(resolved), sort_keys=False, default_flow_style=False)


def _sorted(value):
    if isinstance(value, dict):
        return {k: _sorted(value[k]) for k in sorted(value)}
    return value


def write_resolved(profile: str, config_dir: Path = CONFIG_DIR) -> Path:
    out = config_dir / "resolved.yaml"
    out.write_text(render(profile, config_dir))
    return out


def is_stale(profile: str, config_dir: Path = CONFIG_DIR) -> bool:
    """True when the committed resolved.yaml differs from a fresh render."""
    out = config_dir / "resolved.yaml"
    return not out.is_file() or out.read_text() != render(profile, config_dir)


def main(argv: list[str] | None = None, config_dir: Path = CONFIG_DIR) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", default="demo")
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--validate-only", action="store_true", help="validate defaults and the profile; write nothing")
    mode.add_argument("--check", action="store_true", help="exit 1 if config/resolved.yaml is stale or hand-edited")
    args = parser.parse_args(argv)
    try:
        if args.validate_only:
            render(args.profile, config_dir)
            validate_standards(config_dir)
            print(f"ok: profile {args.profile}")
        elif args.check:
            if is_stale(args.profile, config_dir):
                print("error: config/resolved.yaml is stale or hand-edited; run `make resolve`", file=sys.stderr)
                return 1
            print("ok: config/resolved.yaml is current")
        else:
            print(f"wrote {write_resolved(args.profile, config_dir)}")
    except (FileNotFoundError, TypeError, ConfigError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
