"""Resolve platform config: defaults deep-merged with a profile.

Usage: python config/load.py [--profile demo]
Writes config/resolved.yaml. Deep-merge logic lives only here.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

CONFIG_DIR = Path(__file__).resolve().parent
HEADER = "# GENERATED by config/load.py -- do not edit. Run `make resolve`.\n"


def deep_merge(base: dict, override: dict) -> dict:
    """Return base with override merged in; nested dicts merge, other values replace."""
    out = dict(base)
    for key, value in override.items():
        if isinstance(value, dict) and isinstance(out.get(key), dict):
            out[key] = deep_merge(out[key], value)
        else:
            out[key] = value
    return out


def _read(path: Path) -> dict:
    data = yaml.safe_load(path.read_text()) or {}
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a mapping")
    return data


def resolve(profile: str, config_dir: Path = CONFIG_DIR) -> dict:
    profile_path = config_dir / "profiles" / f"{profile}.yaml"
    if not profile_path.is_file():
        raise FileNotFoundError(f"profile not found: {profile} ({profile_path})")
    return deep_merge(_read(config_dir / "defaults.yaml"), _read(profile_path))


def _sorted(value):
    if isinstance(value, dict):
        return {k: _sorted(value[k]) for k in sorted(value)}
    return value


def write_resolved(profile: str, config_dir: Path = CONFIG_DIR) -> Path:
    resolved = _sorted(resolve(profile, config_dir))
    out = config_dir / "resolved.yaml"
    out.write_text(HEADER + yaml.safe_dump(resolved, sort_keys=False, default_flow_style=False))
    return out


def main(argv: list[str] | None = None, config_dir: Path = CONFIG_DIR) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", default="demo")
    args = parser.parse_args(argv)
    try:
        out = write_resolved(args.profile, config_dir)
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
